services:
    app:
        container_name: app
        networks:
        - sail
        build:
            context: .
            dockerfile: Dockerfile
        image: sail-8.3/app
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        expose:
            - 9000
        volumes:
            - caddy:/data
            - './wallet:/srv/wallet'
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            interval: 2s
            timeout: 20s
            retries: 10
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
          - 8081:80
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          UPLOAD_LIMIT: 300M
          PMA_HOST: mysql  
        links:
          - "mysql:db"
        depends_on:
          - mysql
        networks:
          - sail
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - 'sail-redis:/var/data/redis'
            # - 'sail-redis-data:/var/data/redis'
            # - 'sail-redis-conf:/var/conf/redis'
        environment:
            - REDIS_PASSWORD=my-password
            - REDIS_PORT=6379
            - REDIS_DATABASES=16
        networks:
          - sail
networks:
    sail: null
volumes:
    caddy:
    sail-mysql:
    sail-redis:
    # sail-redis-data:
    # sail-redis-conf: